### ISSUE TITLE
Slow image load from non-S3 server?

### ISSUE THREAD

**Issue by jschell42** [zooniverse/panoptes-cli#167]
I'm using a U-M Library server to host images for [MI-Bug](https://www.zooniverse.org/projects/jmschell/notes-from-nature-mi-bug). I've got direct URLs to the images, which I used to create subjects. Here's an example: 

https://quod.lib.umich.edu/cgi/i/image/api/image/insect2ic:UMMZI-143910:UMMZ-INS-143910/full/3000/0/native.jpg

However, volunteers have mentioned slow image-loading times within the Zooniverse project (as I have noticed). However, when I just click on the link directly, it comes up fine. Posting this issue in the panoptes-cli since I used that to create the subjects, but if it's better addressed elsewhere, I'm happy to repost. Thanks!

**Comment by camallen** [comment]
I visited your project (workflow 14036) and the first image i received has dimensions 10080 × 7560 and is 2.6MB, that is a pretty large file for the browser to download, especially over slower networks. 
https://quod.lib.umich.edu/cgi/i/image/api/image/insect2ic:UMMZI-175908:UMMZ-INS-175908/full/res:0/0/native.jpg

Another test (workflow 14111) yields an image with dims 9680 × 6480 and 1.8MB, again pretty large for the majority of size of screens folks use for our platform.
https://quod.lib.umich.edu/cgi/i/image/api/image/insect2ic:UMMZI-144857:UMMZ-INS-144857/full/res:0/0/native.jpg

Also note, there will be latency from your web server to folks not in the US, which will vary but this will add a delay onto the download time as well. 

Here is a quick test from my laptop in the UK: 
<img width="1272" alt="Screenshot 2020-04-27 at 15 31 47" src="https://user-images.githubusercontent.com/295329/80384059-4e68fb00-889c-11ea-9b63-d7f7f237d22e.png">

Note the waiting time and download time explained as 
> Waiting | Waiting for a response from the server.
> Receiving | Time taken to read the entire response from the server (or cache).

https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details?utm_source=mozilla&utm_medium=devtools-netmonitor&utm_campaign=default#Timings

Also note your image web server doesn't allow this data to be cached by intermediate servers, only the browser cache, which will mean the browser will have to fetch any new image from the server. 

I think the best thing todo is to either resize your images as they are very large for our website, we generally recommend folks try and keep their images under 600KB for use on our platform. Most users will only be able to display a scaled version of the image (due to their computer screen sizes) and the extra image data is transferred but not used in display. 

I'm happy to help answer any questions if you have them but I'm going to close this issue as it's not related to the cli tool nor our platform. I hope this helps.
