### ISSUE TITLE
panoptes info not working

### ISSUE THREAD

**Issue by debboutr** [zooniverse/panoptes-cli#67]
i just install panoptescli from pip, version 0.8 and the command 'panoptes info' isn't recognized. I'm using python 2.7

```
(img) C:\Users\Rdebbout>panoptes info
Usage: panoptes [OPTIONS] COMMAND [ARGS]...

Error: No such command "info".

(img) C:\Users\Rdebbout>panoptes --help
Usage: panoptes [OPTIONS] COMMAND [ARGS]...

Options:
  -e, --endpoint TEXT
  -a, --admin          Enable admin mode. Ignored if you're not logged in as
                       an administrator.
  --help               Show this message and exit.

Commands:
  configure
  project
  subject
  subject-set
  workflow
```

**Comment by astopy** [comment]
Sorry for the confusion -- the `info` command is new and isn't in version 0.8. It'll be in version 1.0 which is due to be released next week.

If you're hoping to upload anything other than images, you'll also need version 1.0 for that. I'd suggest installing the release candidate from GitHub (there shouldn't be any big changes between now and the release of 1.0 anyway):

```
$ pip install -U git+git://github.com/zooniverse/panoptes-cli.git
```
